default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: kindly_development
test:
  <<: *default
  database: kindly_test
production:
  <<: *default
  database: kindly_production
  username: kindly
  password: <%= ENV['KINDLY_DATABASE_PASSWORD'] %>
